server:
  port: 10010
  servlet:
    context-path: /bss

spring:
  # jpa
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  # datasource
  datasource:
    driver-class-name: org.h2.Driver
    # server mode
    url: jdbc:h2:tcp://localhost:9092/~/h2/bss
    # embedded mode
    #url: jdbc:h2:~/h2/bss
    username: admin
    password: admin1234
