server:
  port: 8080
  servlet:
    context-path: /bss

spring:
  # jpa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  # datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/h2/bss
    username: admin
    password: admin1234
